mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  datasource:
  url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: zfy123456
  driver-class-name: com.mysql.cj.jdbc.Driver
  initialization-mode: always
  schema: classpath:sql/schema.sql
  data: classpath:sql/data.sql


logging:
  level:
    com:
      mall:
        MallWeb:
          mapper: debug
